### ISSUE TITLE
Doing a "reset to clean install" deletes buildpad data

### ISSUE THREAD

**Issue by bluenote73** [gw2-addon-loader/GW2-Addon-Manager#117]
Which means that builds one had saved and might not actually have anywhere else would be lost. I don't think this is expected behavior. I don't know if there's data in ARC that people expect to be saved otherwise, but I guess it applies there too if there is. At the very least a specific warning should probably happen? I mean if I uninstall microsoft word, it does not delete all my word documents.

It's worth pointing out that at the moment, you could be forced into a clean reinstall because of various bugs.

**Comment by Friendly0Fire** [comment]
The "reset to clean install" option does in fact explicitly mention that all data will be erased as well. Not a bug, though I will endeavor to create an option more like what you're looking for.
