### ISSUE TITLE
"Unable to initialize 3D output" after installing anything with Addon Manager

### ISSUE THREAD

**Issue by CamdenQ** [gw2-addon-loader/GW2-Addon-Manager#122]
Like the title says, no matter what I install, not just the DirectX 12 proxy, I get this:
![Screenshot 2021-08-08 232705](https://user-images.githubusercontent.com/23227790/128657526-661f9f73-40ce-4c79-8e4b-f03388426586.png)

My GPU supports DirectX 12, my drivers are up to date, and I reinstalled the GPU drivers and DirectX 12 just to be safe. Nothing changes.

The only way I've found to fix the issue once I get that error is to delete my bin64 folder. None of the actions available in the manager fix it.

**Comment by CamdenQ** [comment]
Update, I do not need to delete the entire bin64. Just deleting the d3d9.dll works

**Comment by CamdenQ** [comment]
To be clear, by "fix the issue" I mean once again be able to successfully run GW2. No addons work with this manager for me.

**Comment by marcoboyle** [comment]
I have the same issue. did you ever get a fix for this?

**Comment by leighbc** [comment]
I have this issue when I install arcDPS via the manager.  If I remove arcDPS and just install the Mount Radial, that works fine.  I haven't tried others cause those are the two I want to use.  Do you have the issue with all addons via the manager. or just if arcDPS is included?

**Comment by CamdenQ** [comment]
Why was this closed? This has not been fixed.
