### ISSUE TITLE
[Draeggiar's v1.3.3 pre-alpha] Can't disable SelectRenderer bc folder name mismatch

### ISSUE THREAD

**Issue by kazerniel** [gw2-addon-loader/GW2-Addon-Manager#126]
**Describe the bug**
I'm using @Draeggiar 's v1.3.3 pre-alpha release. Trying to disable [SelectRenderer](https://github.com/megai2/SelectRenderer), but the app is looking for it in a folder named "SelectRender**er**", while it is installed in a folder named "SelectRender".

**To Reproduce**
1. Install SelectRenderer.
2. Try to disable SelectRenderer.

I haven't tried to rename the install folder in case it messes something up.

[config.ini.txt](https://github.com/gw2-addon-loader/GW2-Addon-Manager/files/7173649/config.ini.txt)

![image](https://user-images.githubusercontent.com/5689996/133518764-83a6b1a1-af8c-4fef-b9b8-1eb5f67608b4.png)

**Comment by kazerniel** [comment]
Sort of related: I tried to disable d912pxy at the same time when the critical error occurred and the Addon Manager crashed. After I restarted the manager, d912pxy still appears as active in the addon list, but it's been removed from the actual folder structure, so when I try to disable it again, it gives the same error as above.

**Comment by Friendly0Fire** [comment]
I'm truly sorry but Draeggiar's fork will not be supported here as I'm in the process of rewriting this project.
