### ISSUE TITLE
ArcDPS not loading

### ISSUE THREAD

**Issue by StephyGW2** [gw2-addon-loader/GW2-Addon-Manager#129]
all my addons was working yesterday, but today they're not. 

I've downloaded the addons manager again, aswell as clicked all my addons, reinstalled gw2, anything I can think of.

My friends seem to be working fine, I'm not sure if its me, or somehow I'm getting corrupted files in the download. 

When I manually download ArcDPS from the website, it works fine.

**Comment by StephyGW2** [comment]
Not sure if this helps but.. 

[INFO] core | Addon loader v1.0 (v1.0 r27) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading arcdps
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[WARN] core | Addon "arcdps" is not loaded due to wrong dependency version "d3d9_wrapper". Require v1.0(r0) but have v2.0(r21)
[ERR] core | addons/arcdps/gw2addon_arcdps.dll dependency outdated
[INFO] core | Loading d3d9_wrapper
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system d3d9
[INFO] core | Unloading core addon
[INFO] core | Unloaded

**Comment by Silvermane06** [comment]
I have the same proble, after downloading addon loader v1.4 (since any previous version was broken due to dx11 i assume), It properly installed dx912pxy, but it did not install arcdps.

**Comment by StephyGW2** [comment]
> I have the same proble, after downloading addon loader v1.4 (since any previous version was broken due to dx11 i assume), It properly installed dx912pxy, but it did not install arcdps.

Oh thank goodness I'm not the only one! I blamed my friend for making me manually download ArcDPS, and start renaming it for dx11 nonsense. I've been trying to fix this issue for over 2 hours now with no such luck! I love the addon manager, it keeps all my most used addons in 1 place.

**Comment by MuwuM** [comment]
I know 2 palyer having the excact same issue after the update to v1.4. Even using an older version on a clean gw2 installation did not help. They currently had to wipe bin64-directory and manually install arcdps to get it working. 

There are also some mentions of this issue in the arcdps discord.

**Comment by FaythsRequiem** [comment]
I'm having the same issue.

**Comment by blackhawk1542** [comment]
I saw a new update on Delta's site but somehow the add-on manager is still installing an older version.
I first delete the bin64 folder and the addons folder from GW2. Then I installed the add-on manager v1.4 and all the add-ons including ArcDPS using the manager.
But to make ArcDPS work again, I downloaded the d3d9.dll from the 26th and replace the current one installed by the manager that had a modified date of the 25th. And now ArcDPS is loading. 
Also, I am not using the dx11 from the beta or the dx912pxy add-on.

**Comment by Friendly0Fire** [comment]
There's currently some incompatibilities between the updated addon loader and arcdps, but those should be resolved soon. Since this is not relevant to the addon manager, I will close it here. Unfortunately, arcdps doesn't have an issue tracker for me to refer to.
