### ISSUE TITLE
"Critical Error" addonLoader.dll' already exists

### ISSUE THREAD

**Issue by DokiVino** [gw2-addon-loader/GW2-Addon-Manager#130]
### Please attach a copy of config.yaml or config.ini to the issue.

**Describe the bug**
My addons were not working today (09/25/21). They were working fine yesterday (09/24/21)
I didn't find a related issue to this one, if it exists, I'll gladly close this one.

**To Reproduce**
Game is launched as admin, addon-manager is also launched as admin.

I removed all the content from /bin64, emptied /addons and re-installed Gw2-addon-manager
When I run the application for gw2-addon-manager, I select the directory for my game 'C:\Program Files\Guild Wars 2', 
select arc-dps and gw2radial and press update. 

Open the game, but no success with the addons. 
I launch gw2-addon-manager once more, click update, and I am thrown a "Critical Error" with the following message:

"An unhandled exception occurred. The file 'C:\Program Files\Guild Wars 2\bin64\addonLoader.dll' already exists."

If I delete that file, I get the same message but for another file (i.e: dxdi.dll already exists).

**Additional context**

**don't forget to attach the config file to the issue**

**Comment by nicodemus4802** [comment]
Can confirm error.

**Comment by j0hnyboy** [comment]
I'm also facing the same error

**Comment by Shark8472** [comment]
i can also confirm the error. I deleted the files that gave the error. witch got it to update but i can open the addons + if i update again it gives the sme errors again
![image](https://user-images.githubusercontent.com/79028810/134793565-b10d90f5-3bf5-482f-90ca-5a93fcad1ad0.png)

**Comment by BenKennish** [comment]
I'm also getting this

**Comment by PopSonny** [comment]
yup, i'm also having the same problem.

**Comment by gShadw** [comment]
For this bug , I have a little fix not perfect work
I copy and rename addonLoader.dll to d3d9.dll
launcher and SelectRender+d9d12 work but not arcDps

**Comment by Shark8472** [comment]
does the radial-mount menu work, with that fix? I can live without arc but no radial is a pain. I have fallen to my death twice..

**Comment by DokiVino** [comment]
@Shark8472 I would install them manually. 

go to deltaconnect -> download arcdps -> name it d3d9.dll drop it in /bin64
go to gw2radial -> download -> name it d3d9_chainload.dll -> drop it in /bin64

^ Only works while game is launched as d9, **not** d11 Beta

**Comment by Friendly0Fire** [comment]
Yes, this is an issue with the addon manager not having been updated before the addon loader was updated. The only solution for now is to not run the addon manager until an update has been deployed (sorry, no ETA for now, I'm only just picking up this project).

**Comment by WizardsCreation** [comment]
this is still happening just for anybody that's checking back.

**Comment by Friendly0Fire** [comment]
This should be fixed with this version: https://github.com/gw2-addon-loader/GW2-Addon-Manager/releases/tag/v1.4.1
