### ISSUE TITLE
Unable to locate Guild Wars 2 /bin

### ISSUE THREAD

**Issue by YellowJel** [gw2-addon-loader/GW2-Addon-Manager#131]
Hi,
Running v1.4 Alpha. I don't have GW2 installed in the default folder and the program doesn't detect the installation location. This doesn't happen with v1.2.2

![errorgw2uoaom1 4](https://user-images.githubusercontent.com/91412782/134802949-72645f84-a619-46f8-a798-0698bec4fcee.png)

**Comment by blaskoa** [comment]
I had the same issue. Workaround is to set the custom path ("Select Directory" button) and then restart the addon manager.

**Comment by Friendly0Fire** [comment]
Your game path appears wrong ("GamesD"?), so that's probably the reason. Please report back if the issue persists.

**Comment by Sonseba** [comment]
Issue is that _configurationManager.UserConfig.GamePath gets updated when changing the Game path in the OpeningViewModel, but the _configurationManager.UserConfig.BinFolder doesn't. So setting the path, closing the manager and re-opening it fixes it since that updates the _configurationManager.UserConfig.BinFolder variable when it gets instantiated. 
configuration.DetermineSystemType() should probably be called in the update_button_clicked before the check, rather than in OpeningView()

**Comment by YellowJel** [comment]
> Your game path appears wrong ("GamesD"?), so that's probably the reason. Please report back if the issue persists.

Not wrong, it's the name of the folder

**Comment by YellowJel** [comment]
> I had the same issue. Workaround is to set the custom path ("Select Directory" button) and then restart the addon manager.

> Issue is that _configurationManager.UserConfig.GamePath gets updated when changing the Game path in the OpeningViewModel, but the _configurationManager.UserConfig.BinFolder doesn't. So setting the path, closing the manager and re-opening it fixes it since that updates the _configurationManager.UserConfig.BinFolder variable when it gets instantiated.
> configuration.DetermineSystemType() should probably be called in the update_button_clicked before the check, rather than in OpeningView()

It worked, thanks! I still think this should be considered a bug because it shouldn't be necessary to restart the addon manager, right?

**Comment by Sonseba** [comment]
> 
> 
> > I had the same issue. Workaround is to set the custom path ("Select Directory" button) and then restart the addon manager.
> 
> > Issue is that _configurationManager.UserConfig.GamePath gets updated when changing the Game path in the OpeningViewModel, but the _configurationManager.UserConfig.BinFolder doesn't. So setting the path, closing the manager and re-opening it fixes it since that updates the _configurationManager.UserConfig.BinFolder variable when it gets instantiated.
> > configuration.DetermineSystemType() should probably be called in the update_button_clicked before the check, rather than in OpeningView()
> 
> It worked, thanks! I still think this should be considered a bug because it shouldn't be necessary to restart the addon manager, right?

Yup, I've created a pull requested with a suggested fix for it for Friendly0Fire to review.

**Comment by Friendly0Fire** [comment]
The Redesign definitely won't have that issue, I can assure you that much. Stay tuned!
