### ISSUE TITLE
Addon Manager Update and functionality not working

### ISSUE THREAD

**Issue by mikepaneras** [gw2-addon-loader/GW2-Addon-Manager#147]
Hi! It won't let me update the Addon manager, it just resets every time i re-open it to the older version, add-ons ain't working in game probably because of this and also pops up an error saying a file is missing while not telling me what file it is at the same time when closing the app. Addon manager shows me and installs the newest version of gw2 radial for example tho even in the old version but it won't work.. probably because the addon manager ain't updating and is stack with the dx9 addon loader version. Probably dunno, just wanted to bring out this issue. I also tried to download the 1.4.1 from github directly but throws me to the older version again.

**Comment by Zai-shen** [comment]
+1 pls fix

**Comment by Friendly0Fire** [comment]
1.4.2 fixes the update not appearing to have worked, so please try this and if you have another problem, open a new issue, thanks!
