### ISSUE TITLE
Addon manager causing error report

### ISSUE THREAD

**Issue by ze0t** [gw2-addon-loader/GW2-Addon-Manager#148]
Installed the update manager as instructed by the pop up on my game (Radialmount wheel) read the readme, it pointed me to the update manager

The first time i installed the update manager i installed 3 add on's, ArcDPS, the DX12 proxy, and Radialwheel

when i started the game, i got an instant error report after pressing play. 

tried uninstalling VIA the updatemanager, no change, every time i run the game it causes and error report

uninstalled the game (GW2) completely and reinstalled, game loads

tried the update manager again, this time only using the radial wheel add on

still got the error report

if needed, i can download again and get Screenshots of the error report , but currently reinstalled the game a second time, and a second time it loads after reinstalling..

is there another way to get the radial mount without the update manager?

thanks for any help

using Win10 pro 64 bit

Ryzen build if it's important.

### Please attach a copy of config.yaml or config.ini to the issue.

**Describe the bug**

**To Reproduce**
List steps to reproduce the bug, if possible.

**Additional context**

**don't forget to attach the config file to the issue**

**Comment by Friendly0Fire** [comment]
[Here.](https://github.com/Friendly0Fire/GW2Radial#manual-installation)

**Comment by ze0t** [comment]
Trying now, turns out I have to install the game still 

I put the Dll change already... then ran the game and found out its installing still... Should I do it again once the install is done or I'm good?

**Comment by Friendly0Fire** [comment]
You should be fine!

**Comment by ze0t** [comment]
Didn't work upon loading the game

**Comment by ze0t** [comment]
Will check binds etc first

**Comment by ze0t** [comment]
Yeah the Dll d3d9 is still there but there was no opening pop up and no access to menu with ctrl shift m

**Comment by ze0t** [comment]
if you have discord can jump on that.... otherwise not sure how to access radial menu :(

**Comment by Friendly0Fire** [comment]
The Discord is on one of the buttons in the readme, feel free to join. Otherwise, check if you have a log file in the root GW2 directory, should be called `gw2radial.log`.

**Comment by ze0t** [comment]
i have a text file with that name but when i try to upload it it says it's empty and when i check via notepad, such is that.

**Comment by ze0t** [comment]
I didnt find the discord... but I managed to get it working. Feel free to dm the discord. Thanks so much for all your help and this awesome mount wheel ^_^

**Comment by Friendly0Fire** [comment]
[Here](https://discord.gg/zqeHCEg) you go!

If you could, can you tell me what was wrong and how you fixed it? It'll help us in the future. Thanks and glad to hear it's working!

**Comment by ze0t** [comment]
Definitely m8, it was the Dx11 button.  As soon as I unchecked the  ew dx 11 box I opened the game and the welcome message appeared

**Comment by ze0t** [comment]
New***
