### ISSUE TITLE
Intercepted unhandled exception

### ISSUE THREAD

**Issue by KuanHaoDHuang** [gw2-addon-loader/GW2-Addon-Manager#151]
with the new update, after playing for about 10 to 15 mins I always get this error to appear.

https://i.imgur.com/9MIV4m3.png

**Comment by xivor** [comment]
That error is an Arenanet error.  It could be cause by any of the mods you are using.  Right now with the change in code for the integration of DX11, even when running DX9, there are some mods that may not function properly and require updating.  Some of Arenanets code changes have potentially affected even DX9 users.  For example, if I recall, GW2Radial did not work on native DX9 after the update until @Friendly0Fire made an update.  So, it is possible one of your mods is not updated yet.

 I can confirm that on DX9, ArcDPS and GW2Radial are now functioning, but I am unsure about any others. Also, there may not be any mods except ArcDPS working on DX11 yet. Significant programming updates would need to be made most likely for many of the mods.

The safest option would be to remove all mods for now, and then add them one by one in a controlled fashion. By doing this, you can test the functionality and stability of each.  This would help with problem isolation, so you an figure out what actually is causing it and so you can go to the correct resource.  This is an Addon Manager, but the developer here does not make the mods.  Others provide them, and AddonManager helps you download and install them. In the end, you really need to drill down on what mod is causing the problem so you can get the right support resource.

**Comment by Friendly0Fire** [comment]
That error message is from arcdps, but it's not really telling me anything. Do you have `.dmp` files in your root GW2 folder?

**Comment by KuanHaoDHuang** [comment]
I do, how do I upload the file.(I'm kinda new here)

**Comment by Friendly0Fire** [comment]
Those files have personally identifiable information, so [join our Discord](https://discord.gg/zqeHCEg) and you'll be able to DM them to me.

**Comment by xivor** [comment]
> That error message is from arcdps, but it's not really telling me anything. Do you have `.dmp` files in your root GW2 folder?

Good to know.  I thought for sure I have seen that error from GW2 before. Add that to my notes for how to fix GW2 problems lol.
