### ISSUE TITLE
arcdps with dx9 option on the installer?

### ISSUE THREAD

**Issue by sharpx5** [gw2-addon-loader/GW2-Addon-Manager#153]
When installing arcdps with additional addons like d912pxy, the installer adds the dx11 version of arcdps.  This automatically means that my d912pxy and gw2radial will not work.  I need to stay on the dx9 version of the base game until the other mods update compatibility with dx11. Is there a way to circumvent this issue?

**Comment by Friendly0Fire** [comment]
There is only one version of arcdps. If using arcdps causes issues with DX9, then it's an issue with arcdps.

**Comment by sharpx5** [comment]
Hi,

It inserts the d3d11 file as opposed to d3d9.  Renaming it back to d3d9 doesn't seem to resolve the issue with chain loading the other addons.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
