### ISSUE TITLE
Error 403 on start

### ISSUE THREAD

**Issue by loebaloeba** [gw2-addon-loader/GW2-Addon-Manager#156]
Hello any version of the manager i try to download i can not open, it gives me an error 403 instantly.
Except the very first time i tried to open the newest version, it worked fine installed everything and it gave an error on Raidial and now not a single version wants to open anymore

**Comment by Caryntjen** [comment]
I have the same issue:
![image](https://user-images.githubusercontent.com/3481691/140607283-8178ceeb-62cf-404e-b596-34d95123ac3f.png)

**Comment by CommanderXalvador** [comment]
same

**Comment by TinyBabyOwl** [comment]
Also having this issue.

**Comment by KB0A** [comment]
same here

**Comment by wiruzman** [comment]
{"message":"API rate limit exceeded for 185.181.223.80. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

**Comment by PaterFrog** [comment]
Also getting the 403 error now. Trying to fix issues with DX9 that were somehow caused by the DX12 addon from this manager. Now I can't even get in this manager anymore...

**Comment by cording12** [comment]
I had this issue as well; thanks to @wiruzman for clarifying the problem.

I fixed it by downloading a free VPN and connecting through that (top search results on Google are fine). This then clears the API rate limit so you can launch the addon manager and install whatever you need.

**Comment by MarvIcNet** [comment]
Same error for me.
I was messing around with UOAOM because I has some trouble lauching Arc and Radial at the same time. Deleating and re-donloading the addons. Then after 30 min messing with it I now got this error each time I try to open UOAOM.

![image](https://user-images.githubusercontent.com/17121309/150637194-d715fe4c-b2ab-451e-bf50-09890ce4b6aa.png)

**Comment by wiruzman** [comment]
> Same error for me. I was messing around with UOAOM because I has some trouble lauching Arc and Radial at the same time. Deleating and re-donloading the addons. Then after 30 min messing with it I now got this error each time I try to open UOAOM.
> 
> ![image](https://user-images.githubusercontent.com/17121309/150637194-d715fe4c-b2ab-451e-bf50-09890ce4b6aa.png)

You have to wait until the rate limit is or using a VPN to act like a new client to query the api.

**Comment by Friendly0Fire** [comment]
Any tool using the Github API is stuck with this.
