### ISSUE TITLE
unnecessary redownloads

### ISSUE THREAD

**Issue by arcnmx** [gw2-addon-loader/GW2-Addon-Manager#163]
**Describe the bug**

Without fail, GW2-UOAOM will always download BuildPad as part of the update process, even though it's presumably up-to-date.

**To Reproduce**

Install or update BuildPad. Close GW2-UOAOM and then re-open it, and click `UPDATE`. It will redownload BuildPad again, even though it was just updated a minute ago ago.

> Please attach a copy of config.yaml or config.ini to the issue.

I have an xml instead?

```xml
<?xml version="1.0"?>
<UserConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <LoaderVersion>v1.1</LoaderVersion>
  <BinFolder>bin64</BinFolder>
  <LaunchGame>false</LaunchGame>
  <GamePath>E:\Games\Guild Wars 2\</GamePath>
  <ExeName>Gw2-64.exe</ExeName>
  <Culture>en-US</Culture>
  <AddonsList Hash="54a7df00c282c7cda7d8f04bcc719fc2094fb37f">
    <AddonData>
      <Name>d3d9_wrapper</Name>
      <Version>v2.0</Version>
      <Installed>true</Installed>
      <Disabled>false</Disabled>
    </AddonData>
    <AddonData>
      <Name>arcdps</Name>
      <Version>ff36f6c4d18c195b92da7fab5248cf9c  d3d9.dll
</Version>
      <Installed>true</Installed>
      <Disabled>false</Disabled>
    </AddonData>
    <AddonData>
      <Name>arcdps_bhud</Name>
      <Version>v0.3.1</Version>
      <Installed>true</Installed>
      <Disabled>false</Disabled>
    </AddonData>
    <AddonData>
      <Name>d912pxy</Name>
      <Version>v2.4.4.1</Version>
      <Installed>true</Installed>
      <Disabled>false</Disabled>
    </AddonData>
    <AddonData>
      <Name>arcdps_mechanics</Name>
      <Version>v2.0.0</Version>
      <Installed>true</Installed>
      <Disabled>false</Disabled>
    </AddonData>
    <AddonData>
      <Name>arcdps_boontable</Name>
      <Version>v2.4.3</Version>
      <Installed>true</Installed>
      <Disabled>false</Disabled>
    </AddonData>
    <AddonData>
      <Name>buildPad</Name>
      <Installed>true</Installed>
      <Disabled>false</Disabled>
    </AddonData>
  </AddonsList>
</UserConfig>
```

**Comment by Friendly0Fire** [comment]
BuildPad does not provide version information, so it'll always be redownloaded if selected for updates. Just uncheck the box for it before updating, it also self-updates.

**Comment by arcnmx** [comment]
Right. Since it self-updates, wouldn't it make sense to default it to unchecked and require manual update requests for redownloads? Maybe the application could remember the previous state of the update checkboxes for next launch.

Requesting `https://buildpad.gw2archive.eu/versions/latest` returns a 302 with a url to the latest version, which seems to be a unique link that could be remembered and checked against the last time it was downloaded.

This feels like a dismissive response when there are quite a number of ways to approach the problem :(

**Comment by Friendly0Fire** [comment]
The way the addon manager is currently designed, it doesn't really make sense to start making selective behavior changes like that. Most users will expect addons to be updated without having to tick any box, and if the self-update is changed or anything, I don't want to miss it and end up with the addon being left unchecked and not updated for a lot of people. The overhead of redownloading one addon is minimal, so I'm not particularly worried about that behavior.

If the design ever changes, I'll revisit this topic.

**Comment by arcnmx** [comment]
> The overhead of redownloading one addon is minimal, so I'm not particularly worried about that behavior.

It's really not here; from double-clicking aom -> clicking update -> waiting for BuildPad -> clicking close; over 50% of that time is spent watching and waiting for BuildPad to download for me. I found it frustrating enough to stare at every day that I filed an issue about it :<

I can personally hack around it by setting it to `<Disabled>true</Disabled>` in the config and let it manage updates to itself, but all I can really say is that this interaction has greatly reduced my confidence in using gw2aom. `HEAD` requests exist, `ETag`s exist, `Last-Modified` headers exist, etc; web browsers have had tools to deal with avoiding redundant downloads of cached files for decades and I might suggest taking a hint or two from them maybe .-.

**Comment by Friendly0Fire** [comment]
> I can really say is that this interaction has greatly reduced my confidence in using gw2aom.

I'm sorry, what? Look, you're more than free to make a PR if the problem is so big in your eyes, but to me it's a low priority issue that'll get resolved later down the line after the long list of far more significant issues is dealt with.

**Comment by arcnmx** [comment]
> I'm sorry, what?

Sorry, of course you have limited time and need to prioritise - but if a project closes issues without resolving them, it conveys that its problems aren't likely to be addressed at all.
