### ISSUE TITLE
Game crashes with dxvk

### ISSUE THREAD

**Issue by iagodavids** [gw2-addon-loader/GW2-Addon-Manager#165]
As per title when I try to implement dxvk with select renderer my game crashes and this message pops up ![127542417-0786819e-9b9e-4bb6-b80e-cf3d074a551c](https://user-images.githubusercontent.com/55346650/142738672-a4f58f34-f5e8-4bc2-ad49-3fe6a27bb8e6.png)
I tried updating my graphic card drivers and directx 9, but it's all the same. I also ran dxdiag for more infos about my pc.

![126872582-e4cd275d-783a-45a6-b765-186919cdfa18](https://user-images.githubusercontent.com/55346650/142738740-4e3f12d5-0e70-41a8-a296-52bbb35b1ca1.png)
![126872577-f3d6d3d8-8c2f-4b85-abed-5a7bc5422a15](https://user-images.githubusercontent.com/55346650/142738742-5f32e560-767d-43c9-ae0d-5d83cd8adfa6.png)

**Comment by Friendly0Fire** [comment]
You'll want to report this to the [SelectRenderer](https://github.com/megai2/SelectRenderer) repo, I cannot help you unfortunately.
