### ISSUE TITLE
Configurable graphics that is used to reset the state of the game graphics when app closes or on user action.

### ISSUE THREAD

**Issue by agaertner** [gw2-addon-loader/GW2-Addon-Manager#171]
**Is your feature request related to a problem? Please describe.**

When you open several accounts then want to quit GW2-UOAOM the graphics settings are set up to whatever account was last opened. If I want to continue with a single instance with my main account I close this app. Unfortunately, all alternative accounts are set to lowest graphics possible so that they open as fast as possible. It is cumbersome worrying about login order.

**Describe the solution you'd like**
Being able to set graphics in the apps main settings which can be used to simply reset graphic settngs eg. by either the app closing or when you press a button on its main view somewhere.

Kind Regards

**Comment by Friendly0Fire** [comment]
The addon manager does not touch reset.dat or any other game data settings, so I'm not sure what you're talking about.

**Comment by agaertner** [comment]
oh sorry. Whatever it is the graphics are being set to what was last opened. I wished for it to be reset to what my main account has set. I don't use the app when I wish to just open a single instance with my main account,

**Comment by Friendly0Fire** [comment]
The addon manager also doesn't handle anything related to startup arguments. It sounds like you're confusing this with a launcher like GW2Launcher or Launch Buddy.

**Comment by agaertner** [comment]
My bad! It is like a jungle out here sometimes.
