### ISSUE TITLE
Release for Linux

### ISSUE THREAD

**Issue by ALipAkrohk** [gw2-addon-loader/GW2-Addon-Manager#185]
**Is your feature request related to a problem?**
The new versions of gw2 run much better on linux thanks to lutris and wine-ge, But your software has problems with GNU / Linux.

**Describe the solution you'd like**
Thanks to DotNet 6, your software can work well on Mac and Linux operating systems today. 
Please publish it for other desktop operating systems as well.

**Describe alternatives you've considered**
[GtkSharp](https://github.com/GtkSharp/GtkSharp), [maui](https://github.com/dotnet/maui)
You can also rewrite the software with the help of flutter, which works better than Csharp today.
[Flutter On Desktop](https://flutter.dev/multi-platform/desktop)

**Additional context**
![screenShot](https://s6.uupload.ir/files/screenshot_20220319_192344_70dw.png)

**Comment by Friendly0Fire** [comment]
You're welcome to make a PR with the full rewrite.
