### ISSUE TITLE
Account launched with LB has (considerably) longer loading times than when launched normally

### ISSUE THREAD

**Issue by GBLikan** [gw2-addon-loader/GW2-Addon-Manager#194]
Hey ! Thanks a lot for LB, which I have been enjoying for quite a while now !

Lately on my laptop (4800HS 1660Ti Max Q) I've been noticing a weird behavior : launching a given account with LB will result in significantly longer loading times (up to four times longer) than launching the same account normally, despite both login methods having the very same parameters.

I've done a fresh GW2 install, and a fresh LB install. In LB I registered the account directly from the initial local.dat parameters, no arguments, no addons or injection of any kind.

And yet, I've timed loading into New Kaineng at ~13s while logged in the "normal" way, and at ~40s with LB.

Has anyone experienced the same thing perchance ?

**Comment by dlamkins** [comment]
This repo is for the addon manager, a utility that can be used to manage addons for GW2.

https://github.com/TheCheatsrichter/Gw2_Launchbuddy may be the repo you're looking for.  😃

**Comment by GBLikan** [comment]
I'm deeply sorry, I had both GitHub opened while trying to troubleshoot my issue and posted on the wrong one... I'm also using UOAOM, very appreciated as well ! ;)

**Comment by dlamkins** [comment]
All good.  Good luck and cheers, mate!
