### ISSUE TITLE
frequent starts overload Github API limit, causes unhandled exception

### ISSUE THREAD

**Issue by fmmmlee** [gw2-addon-loader/GW2-Addon-Manager#20]
**Describe the bug**
If the application is closed and restarted too frequently, the API call to Github that occurs on initialization for update-check purposes will get rejected, causing a 403 bad response from the server that throws an unhandled exception. The error message displayed is not particularly descriptive to the user, either.

**To Reproduce**
Open and close application repeatedly until you get the exception. Haven't counted the exact number of times required.

**Additional context**
Ideally, the API caller should handle this exception and display a message to the user indicating that they got a 403 error because of the API limit, instructing them to close the application and try later.

**don't forget to attach the config file to the issue**
(not applicable)

**Comment by marcoValkyriweb** [comment]
Should you rather not store when last checked for an update and just compare to that? If checked within the last hour, don't bother updating.

**Comment by mikerogne** [comment]
Just encountered this myself. Pretty irritating. How long are we locked out when we encounter it?

**Comment by fmmmlee** [comment]
I'm not sure - I usually wait about a half hour to an hour before trying again once I get this error since I'm not sure if continued attempts lengthen the lockout. @marcoValkyriweb's suggestion also makes sense, will add to the project board.
