### ISSUE TITLE
Addons not loading

### ISSUE THREAD

**Issue by Xinroc89** [gw2-addon-loader/GW2-Addon-Manager#205]
I have the most up to date addon manager. I have deleted and redownloaded my addons. when I get into game nothing loads.

gw2al_log says:

[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading arcdps
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loaded arcdps v1.0 r480
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r1
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system dxgi
[[INFO] core | Unloading core addon
[INFO] core | Unloaded
r addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi

**Comment by Wesleyl89** [comment]
I have the same issue. I tried a clean addon install but that didn't work either. 

If I download arcdps from the official source and place it in the gw2 map at least arcdps works, but none of the extensions.

**Comment by soundofyogi** [comment]
.... or the other way round. You should have that file in both locations

**Comment by Exci** [comment]
> I have the same issue. I tried a clean addon install but that didn't work either.
> 
> If I download arcdps from the official source and place it in the gw2 map at least arcdps works, but none of the extensions.
> 
> edit: Ok I got them working again, I got this from the elite insights discord (arcdps) https://discord.com/channels/456611641526845473/1098002444232957962:
> 
> * copy  `dxgi.dll` from `bin64/cef` into the root `Guild Wars 2/` folder

Cheers. I could see the dxgi library was missing but I wasn't sure where to copy it from.

**Comment by Xinroc89** [comment]
This fixed my problems Thanks guys!
